name: myenv  # Name of your Conda environment
channels:
  - defaults, conda-forge, nvidia  # You can add specific channels like "conda-forge" if necessary
dependencies:
  - python=3.12.3
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.2
  - pytorch=2.2.2
  - torchvision=0.19.1
  - torchaudio=2.4.1
  - torchvision=0.10.0
  - cudatoolkit=11.8.0
  - cuda-toolkit=12.1.1
  - shapely=2.0.6
  - yaml=0.2.5
  - pytorch-cuda=12.4
  - pyg=2.5.2
  - matplotlib=3.9.2
  - pip=24.2
